import { GitCompareArrows } from 'lucide-react';
import type { Journey, Workspace } from '../../types/domain';
import { activeActualSnapshot, compareObservedPath, pathsForJourney, plannedPrimaryPath } from '../../lib/actual';

export function ActualPanel({ journey, workspace }: { journey: Journey; workspace: Workspace }) {
  const snapshot = activeActualSnapshot(workspace);
  const paths = pathsForJourney(workspace, journey.id, snapshot);
  const planned = plannedPrimaryPath(journey);
  const top = [...paths].sort((a,b)=>(b.users??b.sessions??b.count??0)-(a.users??a.sessions??a.count??0))[0];
  return <aside className="editor-panel actual-panel"><div className="panel-heading">Planned vs Actual</div>{!snapshot ? <div className="empty-mini"><GitCompareArrows size={22}/><p>No actual-path snapshot selected.</p></div> : !top ? <div className="empty-mini"><GitCompareArrows size={22}/><p>No observed paths are mapped to this journey for {snapshot.period}.</p></div> : (() => { const c = compareObservedPath(journey, top); return <div className="inspector-special"><div className="actual-match"><strong>{c.matchPct}%</strong><span>primary-path match</span></div><div className="property-section"><h4>Planned primary path</h4><div className="mini-path">{planned.map((id,index)=><span key={id}>{index>0&&<em>→</em>}{journey.nodes.find(n=>n.id===id)?.data.label ?? id}</span>)}</div></div><div className="property-section"><h4>Top observed path</h4><strong className="observed-title">{top.label}</strong><div className="mini-path observed">{top.steps.map((step,index)=><span className={step.nodeId?'':'unmapped'} key={`${step.nodeId||step.label}-${index}`}>{index>0&&<em>→</em>}{journey.nodes.find(n=>n.id===step.nodeId)?.data.label ?? step.label ?? 'Unknown step'}</span>)}</div></div><div className="actual-detail-grid"><div><strong>{paths.length}</strong><span>observed paths</span></div><div><strong>{c.missingPlanned.length}</strong><span>planned missing</span></div><div><strong>{c.unmappedActual.length}</strong><span>unmapped actual</span></div></div>{c.missingPlanned.length>0&&<div className="property-section"><h4>Planned steps not observed</h4><ul className="plain-list">{c.missingPlanned.map(id=><li key={id}>{journey.nodes.find(n=>n.id===id)?.data.label ?? id}</li>)}</ul></div>}{c.unmappedActual.length>0&&<div className="property-section"><h4>Observed but not mapped</h4><ul className="plain-list">{c.unmappedActual.map((step,index)=><li key={index}>{step.label ?? step.nodeId ?? 'Unknown step'}</li>)}</ul></div>}</div>; })()}</aside>;
}
